Repository openbase/bco, pull requests merged in 2021-09, with the labels that each got.

#31 Feature/openhab3
  module/device/openhab/build.gradle.kts
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/communication/OpenHABRestCommunicator.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/communication/OpenHABRestConnection.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/communication/TestClient.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/CommandExecutor.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/OpenHABDeviceManager.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/service/OpenHABService.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/ActivationStateOnOffTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/AlarmStateDecimalTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/BatteryStateDecimalTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/BatteryStateOnOffTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/BlindStatePercentTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/BlindStateStopMoveTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/BlindStateUpDownTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/BrightnessStateHSBTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/BrightnessStateOnOffTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/BrightnessStatePercentTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/ButtonStateOnOffTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/ColorStateHSBTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/ColorStateOnOffTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/ColorStatePercentTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/ContactStateOpenClosedTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/DoorStateOpenClosedTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/HandleStateStringTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/IlluminanceStateDecimalTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/MotionStateDecimalTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/MotionStateOnOffTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/PowerConsumptionStateDecimalTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/PowerStateHSBTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/PowerStateOnOffTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/PowerStatePercentTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/PresenceStateOnOffTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/ServiceStateCommandTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/ServiceStateCommandTransformerPool.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/ServiceTypeCommandMapping.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/SmokeStateDecimalTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/StandbyStateOnOffTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/TamperStateDecimalTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/TamperStateOnOffTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/TemperatureStateDecimalTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/manager/transform/WindowStateOpenClosedTypeTransformer.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/registry/diff/IdentifiableEnrichedItemDTO.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/registry/diff/IdentifiableEnrichedThingDTO.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/registry/synchronizer/AbstractSSEObservable.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/registry/synchronizer/DeviceUnitThingSynchronization.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/registry/synchronizer/InboxAddedObservable.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/registry/synchronizer/InboxApprover.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/registry/synchronizer/InboxUpdatedObservable.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/registry/synchronizer/ItemObservable.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/registry/synchronizer/ItemUnitSynchronization.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/registry/synchronizer/OpenHABItemProcessor.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/registry/synchronizer/SynchronizationProcessor.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/registry/synchronizer/ThingDeviceUnitSynchronization.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/registry/synchronizer/ThingObservable.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/registry/synchronizer/ThingUnitSynchronization.java
  module/device/openhab/src/main/java/org/openbase/bco/device/openhab/registry/synchronizer/UnitThingSynchronization.java
  module/device/openhab/src/test/org/openbase/bco/device/openhab/manager/transform/ServiceTypeCommandMappingTest.java
Labels: tested, code approved

#32 Make gradle build the bco-manager-device-openhab binary
  module/device/openhab/build.gradle.kts
Labels: tested

#33 Setup Unit Tests for Github Actions
  .github/workflows/build-and-test.yml
  .github/workflows/deploy-docker.yml
Labels: review requested

#34 Feature/introduce app base module
  .idea/compiler.xml
  .idea/vcs.xml
  module/app/base/build.gradle.kts
  module/app/util/src/main/java/org/openbase/bco/app/util/launch/BCOTestLauncher.java
  settings.gradle.kts
Labels: review requested
